PREFIX rdf:			<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc:			<http://purl.org/dc/elements/1.1/>
PREFIX dcterms:		<http://purl.org/dc/terms/>
PREFIX prov:		<http://www.w3.org/ns/prov#>
PREFIX calli:		<http://callimachusproject.org/rdf/2009/framework#>
PREFIX mecomp:		<http://rdf.myexperiment.org/ontologies/components/>
PREFIX swowscomp:	<http://swows.org/2014/09/components#>
PREFIX df:			<http://www.swows.org/2012/06/dataflow#>

CONSTRUCT {
	?dfRoot df:hasComponent ?dsConsumer.
    ?dsConsumer
    	a df:DatasetConsumer;
		df:defaultInput
			[ 	a df:Merger;
				df:input ?input ]
}
WHERE {
	SERVICE ?dfEndpoint {
 		?dfRoot	mecomp:has-component ?dsConsumer.
 		?dsConsumer a ?dsConsumerClass.
 		FILTER(?dsConsumerClass IN
 					(	swowscomp:TransformProcessor,
 						swowscomp:Store,
 						swowscomp:DataflowProcessor ) ).
		?input
			a mecomp:Input, swowscomp:isInDefaultInput;
			mecomp:for-component ?dsConsumer.
 	}
}