PREFIX df:      <http://www.swows.org/dataflow#>
PREFIX swi:     <http://www.swows.org/instance#>
PREFIX sp:      <http://spinrdf.org/sp#>
PREFIX spx:     <http://www.swows.org/spinx#>
PREFIX bn:      <http://www.swows.org/instance/.well-known/genid/>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

  DELETE {
    ?sA ?pA ?parentNamedGraph.
    ?parentNamedGraph
      a sp:NamedGraph ;
      spx:element ?namedGraph .
    ?namedGraph a sp:NamedGraph .
  }
  INSERT {
    ?sA ?pA ?namedGraph.
  }
  WHERE {
    ?sA ?pA ?parentNamedGraph.
    ?parentNamedGraph
      a sp:NamedGraph ;
      spx:element ?namedGraph .
    ?namedGraph a sp:NamedGraph .
    FILTER
      NOT EXISTS {
        ?anyGPNamedGraph2
          a sp:NamedGraph ;
          spx:element ?parentNamedGraph .
      } .
  }
    
